//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry_Details
    {
        public string entryId { get; set; }
        public string materialId { get; set; }
        public double entryNum { get; set; }
        public string MaterialLotNum { get; set; }
        public string Unit { get; set; }
        public string whId { get; set; }
    
        public virtual Entrys Entrys { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
