//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrys
    {
        public string entryId { get; set; }
        public string memId { get; set; }
        public string whId { get; set; }
        public string materialId { get; set; }
        public int entryNum { get; set; }
        public string Unit { get; set; }
        public System.DateTime entryTime { get; set; }
        public string materialLotNo { get; set; }
        public string entryNotes { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Members Members { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
