//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materail.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Material_ManagementEntities : DbContext
    {
        public Material_ManagementEntities()
            : base("name=Material_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrators> Administrators { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Entry_Derails> Entry_Derails { get; set; }
        public virtual DbSet<Entrys> Entrys { get; set; }
        public virtual DbSet<Material_Details> Material_Details { get; set; }
        public virtual DbSet<Material_Request> Material_Request { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<PO> PO { get; set; }
        public virtual DbSet<POR> POR { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
        public virtual DbSet<Entry_Details> Entry_Details { get; set; }
    }
}
