//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public string orderId { get; set; }
        public string materialId { get; set; }
        public double orderNum { get; set; }
        public string Unit { get; set; }
        public decimal orderUnitPrice { get; set; }
        public Nullable<float> orderDiscount { get; set; }
        public System.DateTime orderDate { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
