//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales()
        {
            this.Sale_Details = new HashSet<Sale_Details>();
        }
    
        public string saleId { get; set; }
        public string memId { get; set; }
        public string saleAddress { get; set; }
        public byte delType { get; set; }
        public byte saleStatus { get; set; }
        public System.DateTime saleCreateTime { get; set; }
        public Nullable<System.DateTime> saleFinishTime { get; set; }
        public string saleNotes { get; set; }
        public string cusId { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Members Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_Details> Sale_Details { get; set; }
    }
}
